version: '3.4'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      target: php-${APP_ENV}
    user: "1000:1000"
    depends_on:
      - opensearch-ldap-node1
      - db
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/app:rw
      - home-dir:/home/user
    working_dir: /app
    environment:
      HOME: /home/user
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - default
    ports:
      - "3316:3306"
  opensearch-ldap-node1:
    image: opensearchproject/opensearch:1.3.0
    container_name: opensearch-ldap-node1
    environment:
      - plugins.security.disabled=true
      - cluster.name=opensearch-ldap-cluster
      - node.name=opensearch-ldap-node1
      - discovery.seed_hosts=opensearch-ldap-node1
      - cluster.initial_master_nodes=opensearch-ldap-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      # - "DISABLE_INSTALL_DEMO_CONFIG=true" # disable demo config see https://opensearch.org/docs/latest/opensearch/install/docker-security/
    # volumes:
    #   - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - default
  # cerebro:
  #   image: lmenezes/cerebro
  #   platform: linux/arm64
  #   ports:
  #    - "9002:9000"
  #   networks:
  #     - default
networks:
  default:
    driver: bridge

volumes:
  elasticsearch-data:
  home-dir:
